name: Build & Package ProxyCores

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    name: Build ProxyCores for Linux AMD64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl wget unzip tar git build-essential cmake pkg-config gn ninja-build protobuf-compiler clang libssl-dev python3 python3-pip
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create working directory
      run: mkdir -p build/proxycores

    - name: Download brook
      run: |
        wget -O build/proxycores/brook https://github.com/txthinking/brook/releases/latest/download/brook-linux-amd64
        chmod +x build/proxycores/brook

    - name: Download hysteria
      run: |
        wget -O build/proxycores/hysteria https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64
        chmod +x build/proxycores/hysteria

    - name: Download juicity-client
      run: |
        wget -O build/proxycores/juicity-client https://github.com/juicity/juicity/releases/latest/download/juicity-client-linux-amd64
        chmod +x build/proxycores/juicity-client

    - name: Download mihomo
      run: |
        wget -O build/proxycores/mihomo https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64
        chmod +x build/proxycores/mihomo

    - name: Download naiveproxy
      run: |
        wget https://github.com/klzgrad/naiveproxy/releases/latest/download/naiveproxy-linux-x64.tar.xz
        tar -xf naiveproxy-linux-x64.tar.xz
        mv naiveproxy*/naive build/proxycores/naiveproxy
        chmod +x build/proxycores/naiveproxy

    - name: Download overtls
      run: |
        wget -O build/proxycores/overtls https://github.com/zhenorzz/OverTLS/releases/latest/download/overtls-linux-amd64
        chmod +x build/proxycores/overtls

    - name: Download sing-box
      run: |
        wget -O build/proxycores/sing-box https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-linux-amd64
        chmod +x build/proxycores/sing-box

    - name: Download and extract tuic
      run: |
        wget https://github.com/EAimTY/tuic/releases/latest/download/tuic-server-linux-amd64 -O build/proxycores/tuic-server
        chmod +x build/proxycores/tuic-server

    - name: Download v2ray
      run: |
        wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip v2ray-linux-64.zip -d v2ray-core
        mv v2ray-core/v2ray build/proxycores/v2ray
        chmod +x build/proxycores/v2ray

    - name: Download xray
      run: |
        wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
        unzip Xray-linux-64.zip -d xray-core
        mv xray-core/xray build/proxycores/xray
        chmod +x build/proxycores/xray

    - name: Package all binaries
      run: |
        cd build
        tar -czf proxycores-linux-amd64.tar.gz proxycores

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxycores-linux-amd64
        path: build/proxycores-linux-amd64.tar.gz
